### ISSUE TITLE
Simplify the getCookie function

### ISSUE THREAD

**Issue by itsag** [noahgsolomon/Codefolio-frontend#5]
https://github.com/noahgsolomon/Codefolio-frontend/blob/e01cfbd8327c813b299a52f5405540c59560bf79/src/auth/isAuthenticated.tsx#L1

**Comment by noahgsolomon** [comment]
I actually don't even use this isAuthenticate anymore since I set the session id in the users cookies so it is sent by default, so deleting this file 👍
